Text Files:
  - ".txt"

PDF Files:
  - ".pdf"

PPT Files:
  - ".ppt"
  - ".pptx"

Word Files:
  - ".doc"
  - ".docx"

Excel Files:
  - ".xlsx"
  - ".xls"

CSV Files:
  - ".csv"

Video Files:
  - ".mkv"
  - ".mp4"
  - ".avi"

Audio Files:
  - ".mp3"
  - ".wav"

Windows Installer Files:
  - ".exe"
  - ".msi"

APK Files:
  - ".apk"

Image Files:
  - ".jpg"
  - ".png"
  - ".jpeg"
  - ".bmp"
  - ".webp"
  - ".tif"
  - ".tiff"
  - ".svg"

Gif Files:
  - ".gif"

Python Files:
  - ".py"

Zip Files:
  - ".zip"
  - ".rar"
  - ".7z"
